6       header
# Generated by DREAM.3D
grid    a 30    b 30    c 30
size    x 6.000    y 6.000    z 6.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 27000
1 to      27000