6       header
# Generated by DREAM.3D
grid    a 30    b 30    c 30
size    x 7.500    y 7.500    z 7.500
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 27000
1 to      27000