6       header
# Generated by DREAM.3D
grid    a 20    b 20    c 20
size    x 4.000    y 4.000    z 4.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 8000
1 to       8000