6       header
# Generated by DREAM.3D
grid    a 50    b 50    c 50
size    x 15.000    y 15.000    z 15.000
origin    x 0.000    y 0.000    z 0.000
homogenization  1
microstructures 125000
1 to     125000